# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 200b9fa200ef9dda796e9a48a858b2ef2b0528a8abc77810dfe04b953a8f39b08bfdeb089a11b7be371db290f305fd994b263938e9f177dd3387d9e1dce43483

test:
  secret_key_base: e2415345caf8fe42cde6cf4be8469757dec89deb905a69ff771c492ba7607438133de6be7c7c4a6f474d99b5afe2279bd8dd7b90c77e7952ef8805be8914a327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
